kind: Model
apiVersion: v1alpha5
metadata:
  displayName: SHETran
  type: Modelling
  name: shetran
  summary: SHETran is a physically-based spatially-distributed hydrological model.
  description: >
    SHETran is a model for water flow, solute and sediment transport in river catchments.
    SHETran is a finite-difference model in which the physics-based governing partial differential equations for flow and transport are solved on a three-dimensional grid.
    SHETran is a physically-based, spatially-distributed (PBSD) modelling system.
    The plan area of the catchment in SHETran is usually in the range of one to a few thousand square kilometers and the horizontal depth of the subsurface is usually less than 100m.
spec:
  inputs:
    dataslots:
      - name: SHETran input files
        description: SHETran input files
        default:
          - uid: b6ae4273-4251-4980-ab7c-9fcacd7595af
            versionUid: bdb42828-e581-4a1d-8a0a-afcd634d4a2a
        path: inputs
        required: false
