name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t shetran-dafni .

      - name: test return period
        run: docker run -v $PWD/data:/data --env PYTHONUNBUFFERED=1 shetran-dafni
